-- VFXData CLEAN FIX (short version)
local RS = game:GetService("ReplicatedStorage")
local m = RS:FindFirstChild("VFXData") or Instance.new("ModuleScript")
m.Name = "VFXData"
m.Parent = RS
m.Source = [==[
local V = {}
V.AuraMap = {["Flicker"]="Smoke Mist",["Spark"]="Smoke Mist",["Glow"]="Stardust",["Ember"]="Fire Burst",["Surge"]="Crystal Aura",["Bloom"]="Stardust",["Spirit Bomb"]="Fire Burst",["Tempest"]="Crystal Aura",["Nine-Tails"]="Fire Burst",["Eclipse"]="Shadow Flame",["Conqueror Haki"]="Holy Burst",["Cursed Energy"]="Shadow Flame",["Hollow Mask"]="Shadow Flame",["Genesis"]="Divine Wind"}
V.TierVFX = {Common="Smoke Mist",Uncommon="Stardust",Rare="Fire Burst",Epic="Crystal Aura",Legendary="Holy Burst",Mythic="Divine Wind"}
V.VFX = {}
V.VFX["Smoke Mist"] = {Name="Smoke Mist",Effects={{Type="Smoke",Part="HumanoidRootPart",Color=Color3.fromRGB(150,150,150),Size=1.2,Opacity=0.4,RiseAcceleration=1.5},{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new(Color3.fromRGB(160,160,160)),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,2),NumberSequenceKeypoint.new(1,4)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.6),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(3,5),Rate=15,Speed=NumberRange.new(1,2),SpreadAngle=Vector2.new(180,180),Acceleration=Vector3.new(0,1,0)}}}
V.VFX["Stardust"] = {Name="Stardust",Effects={{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new(Color3.fromRGB(255,255,220)),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,0.3),NumberSequenceKeypoint.new(0.5,0.8),NumberSequenceKeypoint.new(1,0.1)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(1.5,3),Rate=40,Speed=NumberRange.new(2,4),SpreadAngle=Vector2.new(45,45),Acceleration=Vector3.new(0,3,0),LightEmission=1,Texture="rbxassetid://243660364"},{Type="Light",Part="HumanoidRootPart",Color=Color3.fromRGB(255,255,200),Brightness=1,Range=8}}}
V.VFX["Fire Burst"] = {Name="Fire Burst",Effects={{Type="Fire",Part="HumanoidRootPart",Color=Color3.fromRGB(255,100,30),SecondaryColor=Color3.fromRGB(255,200,50),Size=2.5,Heat=15},{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new({NumberSequenceKeypoint.new(0,Color3.fromRGB(255,200,50)),NumberSequenceKeypoint.new(0.5,Color3.fromRGB(255,100,30)),NumberSequenceKeypoint.new(1,Color3.fromRGB(150,30,0))}),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,1.5),NumberSequenceKeypoint.new(1,0.2)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.3),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(0.8,1.5),Rate=50,Speed=NumberRange.new(5,10),SpreadAngle=Vector2.new(15,15),Acceleration=Vector3.new(0,10,0),LightEmission=0.8},{Type="Light",Part="HumanoidRootPart",Color=Color3.fromRGB(255,120,30),Brightness=2,Range=12}}}
V.VFX["Crystal Aura"] = {Name="Crystal Aura",Effects={{Type="Particle",Part="UpperTorso",Color=ColorSequence.new(Color3.fromRGB(100,180,255)),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,1),NumberSequenceKeypoint.new(0.5,2),NumberSequenceKeypoint.new(1,0.5)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.2),NumberSequenceKeypoint.new(1,0.8)}),Lifetime=NumberRange.new(1.5,2.5),Rate=35,Speed=NumberRange.new(3,6),SpreadAngle=Vector2.new(360,360),Acceleration=Vector3.new(0,1,0),LightEmission=0.8,Rotation=NumberRange.new(0,360)},{Type="Light",Part="UpperTorso",Color=Color3.fromRGB(100,180,255),Brightness=1.5,Range=10}}}
V.VFX["Shadow Flame"] = {Name="Shadow Flame",Effects={{Type="Fire",Part="HumanoidRootPart",Color=Color3.fromRGB(80,0,120),SecondaryColor=Color3.fromRGB(40,0,60),Size=3,Heat=10},{Type="Smoke",Part="HumanoidRootPart",Color=Color3.fromRGB(40,0,60),Size=2,Opacity=0.5,RiseAcceleration=2},{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new({NumberSequenceKeypoint.new(0,Color3.fromRGB(100,0,150)),NumberSequenceKeypoint.new(1,Color3.fromRGB(20,0,40))}),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,2),NumberSequenceKeypoint.new(1,0.5)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.2),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(1.5,3),Rate=30,Speed=NumberRange.new(2,5),SpreadAngle=Vector2.new(30,30),Acceleration=Vector3.new(0,5,0),LightEmission=0.3},{Type="Light",Part="HumanoidRootPart",Color=Color3.fromRGB(100,0,150),Brightness=1,Range=10}}}
V.VFX["Holy Burst"] = {Name="Holy Burst",Effects={{Type="Light",Part="HumanoidRootPart",Color=Color3.fromRGB(255,255,220),Brightness=3,Range=18},{Type="Particle",Part="UpperTorso",Color=ColorSequence.new(Color3.fromRGB(255,255,240)),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,1),NumberSequenceKeypoint.new(0.5,3),NumberSequenceKeypoint.new(1,0.5)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0),NumberSequenceKeypoint.new(0.7,0.3),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(1,2),Rate=60,Speed=NumberRange.new(8,15),SpreadAngle=Vector2.new(180,180),Acceleration=Vector3.new(0,2,0),LightEmission=1,Texture="rbxassetid://243660364"},{Type="Particle",Part="Head",Color=ColorSequence.new(Color3.fromRGB(255,255,200)),Size=NumberSequence.new(0.5),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.5),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(2,4),Rate=20,Speed=NumberRange.new(0,1),SpreadAngle=Vector2.new(45,45),LightEmission=1,Texture="rbxassetid://243660364"},{Type="Light",Part="Head",Color=Color3.fromRGB(255,255,180),Brightness=2,Range=8}}}
V.VFX["Divine Wind"] = {Name="Divine Wind",Effects={{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new({NumberSequenceKeypoint.new(0,Color3.fromRGB(0,255,200)),NumberSequenceKeypoint.new(0.5,Color3.fromRGB(0,200,255)),NumberSequenceKeypoint.new(1,Color3.fromRGB(100,255,255))}),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,2),NumberSequenceKeypoint.new(0.5,4),NumberSequenceKeypoint.new(1,1)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0.2),NumberSequenceKeypoint.new(1,0.9)}),Lifetime=NumberRange.new(1,2),Rate=80,Speed=NumberRange.new(10,20),SpreadAngle=Vector2.new(180,180),Acceleration=Vector3.new(0,15,0),LightEmission=1,Rotation=NumberRange.new(0,360)},{Type="Particle",Part="HumanoidRootPart",Color=ColorSequence.new(Color3.fromRGB(0,255,220)),Size=NumberSequence.new({NumberSequenceKeypoint.new(0,0.5),NumberSequenceKeypoint.new(1,2)}),Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0),NumberSequenceKeypoint.new(1,1)}),Lifetime=NumberRange.new(0.5,1),Rate=40,Speed=NumberRange.new(15,25),SpreadAngle=Vector2.new(45,45),Acceleration=Vector3.new(0,5,0),LightEmission=1},{Type="Light",Part="HumanoidRootPart",Color=Color3.fromRGB(0,255,200),Brightness=3,Range=20}}}
function V.GetVFXForAura(auraName,tier)
	if V.AuraMap[auraName] and V.VFX[V.AuraMap[auraName]] then return V.VFX[V.AuraMap[auraName]] end
	local cv=game:GetService("ReplicatedStorage"):FindFirstChild("CustomVFX")
	if cv then local r=cv:FindFirstChild(auraName) if r then return{Name=auraName,Effects={{Type="Model",TemplateName=auraName,Part="HumanoidRootPart"}}} end end
	if tier and V.TierVFX[tier] then return V.VFX[V.TierVFX[tier]] end
	return nil
end
return V
]==]
print("✅ VFXData CLEAN FIX applied! Now press Play and test!")
