-- WeatherClient skybox fix (short)
local SPS=game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts")
local function f(c,n,p) local i=p:FindFirstChild(n) if i and i.ClassName~=c then i:Destroy() i=nil end if not i then i=Instance.new(c) i.Name=n i.Parent=p end return i end
f("LocalScript","WeatherClient",SPS).Source=[==[
local P=game:GetService("Players") local RS=game:GetService("ReplicatedStorage") local TS=game:GetService("TweenService") local L=game:GetService("Lighting") local SG=game:GetService("StarterGui")
local pl=P.LocalPlayer local pg=pl:WaitForChild("PlayerGui") local R=RS:WaitForChild("Remotes") local WCE=R:WaitForChild("WeatherChangedEvent") local CTE=R:WaitForChild("ChatTipEvent") local CAE=R:WaitForChild("ChatAnnounceEvent") local WD=require(RS:WaitForChild("WeatherData"))
local VH=50 local TT=3 local BD=5
for _,c in ipairs(pg:GetChildren()) do if c.Name=="WeatherGui" then c:Destroy() end end
local g=Instance.new("ScreenGui") g.Name="WeatherGui" g.ResetOnSpawn=false g.IgnoreGuiInset=true g.DisplayOrder=15 g.Parent=pg
local b=Instance.new("TextLabel") b.Size=UDim2.fromScale(0.7,0.08) b.Position=UDim2.fromScale(0.15,0.04) b.Text="" b.Font=Enum.Font.GothamBlack b.TextScaled=true b.BackgroundColor3=Color3.fromRGB(20,20,35) b.TextColor3=Color3.fromRGB(255,255,255) b.BackgroundTransparency=1 b.Visible=false local bc=Instance.new("UICorner") bc.CornerRadius=UDim.new(0.15,0) bc.Parent=b b.Parent=g
local cv=nil local wo=false
local function clV() if cv then cv:Destroy() cv=nil end end
local function apV(particles) clV() if not particles or #particles==0 then return end local ch=pl.Character if not ch then return end local rt=ch:FindFirstChild("HumanoidRootPart") if not rt then return end cv=Instance.new("Part") cv.Name="WeatherVFX" cv.Size=Vector3.new(1,1,1) cv.Transparency=1 cv.CanCollide=false cv.CanQuery=false cv.Anchored=false cv.Massless=true local w=Instance.new("Weld") w.Part0=rt w.Part1=cv w.C0=CFrame.new(0,VH,0) w.Parent=cv cv.Parent=ch for _,c in ipairs(particles) do local e=Instance.new("ParticleEmitter") e.Color=ColorSequence.new(c.Color or Color3.fromRGB(255,255,255)) e.Size=c.Size or NumberSequence.new(2) e.Transparency=c.Transparency or NumberSequence.new(0) e.Lifetime=c.Lifetime or NumberRange.new(5,10) e.Rate=c.Rate or 100 e.Speed=c.Speed or NumberRange.new(5,10) e.SpreadAngle=c.SpreadAngle or Vector2.new(45,45) e.Acceleration=c.Acceleration or Vector3.new(0,0,0) if c.Texture and c.Texture~="" then e.Texture=c.Texture end e.Parent=cv end end
local function apS(skybox) if not skybox or #skybox~=6 then return end local s=L:FindFirstChildOfClass("Sky") if not s then s=Instance.new("Sky") s.Parent=L end pcall(function() s.SkyboxBk=skybox[1] s.SkyboxDn=skybox[2] s.SkyboxFt=skybox[3] s.SkyboxLf=skybox[4] s.SkyboxRt=skybox[5] s.SkyboxUp=skybox[6] end) end
local function apL(lc) if not lc then return end TS:Create(L,TweenInfo.new(TT,Enum.EasingStyle.Sine,Enum.EasingDirection.Out),{ClockTime=lc.ClockTime or 14,FogColor=lc.FogColor or Color3.fromRGB(199,217,240),FogEnd=lc.FogEnd or 100000,Ambient=lc.Ambient or Color3.fromRGB(128,128,128),OutdoorAmbient=lc.OutdoorAmbient or Color3.fromRGB(128,128,128),Brightness=lc.Brightness or 2,ColorShift_Top=lc.ColorShift_Top or Color3.fromRGB(0,0,0),ColorShift_Bottom=lc.ColorShift_Bottom or Color3.fromRGB(0,0,0)}):Play() end
local function shB(txt,col) if not txt or txt=="" then return end b.Text=txt b.TextColor3=col or Color3.fromRGB(255,255,255) b.Visible=true b.BackgroundTransparency=0.3 b.TextTransparency=0 b.Position=UDim2.fromScale(0.15,-0.1) TS:Create(b,TweenInfo.new(0.5,Enum.EasingStyle.Back,Enum.EasingDirection.Out),{Position=UDim2.fromScale(0.15,0.04)}):Play() task.delay(BD,function() TS:Create(b,TweenInfo.new(0.5,Enum.EasingStyle.Sine,Enum.EasingDirection.In),{BackgroundTransparency=1,TextTransparency=1}):Play() task.wait(0.5) b.Visible=false end) end
WCE.OnClientEvent:Connect(function(info) wo=(info.Name~="Clear") apL(info.Lighting) apV(info.Particles) apS(info.Skybox) shB(info.BannerText,info.BannerColor) end)
local tc=WD.TimeCycle if tc.Enabled then L.ClockTime=tc.StartTime or 6 local hps=24/((tc.DayDurationMinutes or 10)*60) task.spawn(function() while true do if not wo then L.ClockTime=(L.ClockTime+hps*0.1)%24 end task.wait(0.1) end end) end
pl.CharacterAdded:Connect(function() task.wait(1) local v=RS:FindFirstChild("CurrentWeather") if v and v.Value~="Clear" then local w=WD.GetByName(v.Value) if w then apV(w.Particles) end end end)
CTE.OnClientEvent:Connect(function(msg) pcall(function() SG:SetCore("ChatMakeSystemMessage",{Text=msg,Color=Color3.fromRGB(255,215,0),Font=Enum.Font.SourceSansBold,TextSize=18}) end) end)
CAE.OnClientEvent:Connect(function(info) pcall(function() SG:SetCore("ChatMakeSystemMessage",{Text="⭐ "..info.Player.." has obtained "..info.Name.."! ("..info.Tier..")",Color=info.Color or Color3.fromRGB(255,215,0),Font=Enum.Font.SourceSansBold,TextSize=18}) end) end)
print("WeatherClient loaded! (skybox fixed)")
]==]
print("✅ WeatherClient fixed!")
